export const cardData = [
  {
    _id: "001",
    country: "США",
    director: "Иван Васильев",
    duration: "96",
    year: "2022",
    description: "Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.",
    image: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    trailerLink: "https://www.youtube.com/watch?v=HZ3WvUfPDto",
    nameRU: "Очень хороший фильм 1 супер большое название",
    nameEN: "So good film",
    thumbnail: "https://v1.popcornnews.ru/upload/image/1(540).jpg",
    movieId: "25"
  },
  {
    _id: "002",
    country: "США",
    director: "Иван Васильев",
    duration: "96",
    year: "2022",
    description: "Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.",
    image: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    trailerLink: "https://www.youtube.com/watch?v=HZ3WvUfPDto",
    nameRU: "Очень хороший фильм 1",
    nameEN: "So good film",
    thumbnail: "https://www.kino-teatr.ru/movie/pos",
    movieId: "24"
  },
  {
    _id: "003",
    country: "США",
    director: "Иван Васильев",
    duration: "96",
    year: "2022",
    description: "Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.",
    image: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    trailerLink: "https://www.youtube.com/watch?v=HZ3WvUfPDto",
    nameRU: "Очень хороший фильм 1",
    nameEN: "So good film",
    thumbnail: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    movieId: "23"
  },
  {
    _id: "004",
    country: "США",
    director: "Иван Васильев",
    duration: "96",
    year: "2022",
    description: "Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.",
    image: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    trailerLink: "https://www.youtube.com/watch?v=HZ3WvUfPDto",
    nameRU: "Очень хороший фильм 1",
    nameEN: "So good film",
    thumbnail: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    movieId: "20"
  },
  {
    _id: "005",
    country: "США",
    director: "Иван Васильев",
    duration: "50",
    year: "2022",
    description: "Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.",
    image: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    trailerLink: "https://www.youtube.com/watch?v=HZ3WvUfPDto",
    nameRU: "Очень хороший фильм 1",
    nameEN: "So good film",
    thumbnail: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    movieId: "15"
  },
  {
    _id: "006",
    country: "США",
    director: "Иван Васильев",
    duration: "96",
    year: "2022",
    description: "Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.",
    image: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    trailerLink: "https://www.youtube.com/watch?v=HZ3WvUfPDto",
    nameRU: "Очень хороший фильм 1",
    nameEN: "So good film",
    thumbnail: "https://www.dejurka.ru/wp-content/uploads/2012/05/lord-of-rings.jpg",
    movieId: "35"
  },
  {
    _id: "007",
    country: "США",
    director: "Иван Васильев",
    duration: "96",
    year: "2022",
    description: "Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.",
    image: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    trailerLink: "https://www.youtube.com/watch?v=HZ3WvUfPDto",
    nameRU: "Очень хороший фильм 1",
    nameEN: "So good film",
    thumbnail: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    movieId: "45"
  },
  {
    _id: "008",
    country: "США",
    director: "Иван Васильев",
    duration: "96",
    year: "2022",
    description: "Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.",
    image: "https://www.kino-teatr.ru/movie/poster/159821/139936.jpg",
    trailerLink: "https://www.youtube.com/watch?v=HZ3WvUfPDto",
    nameRU: "Очень хороший фильм 1",
    nameEN: "So good film",
    thumbnail: "https://i0.wp.com/lamcdn.net/lookatme.ru/post_image-image/EIcjJT5CSzN-R9EYFh8gSw-article.jpg",
    movieId: "29"
  },
]